import { FigureBaseTypes } from "@/types/figure";
import { GameFieldType } from "@/types/gameField";

export const DEFAIULT_FIELD: GameFieldType = [
    // Row 1
    {type: FigureBaseTypes.rook, color: "black"},
    {type: FigureBaseTypes.knight, color: "black"},
    {type: FigureBaseTypes.bishop, color: "black"},
    {type: FigureBaseTypes.queen, color: "black"},
    {type: FigureBaseTypes.king, color: "black"},
    {type: FigureBaseTypes.bishop, color: "black"},
    {type: FigureBaseTypes.knight, color: "black"},
    {type: FigureBaseTypes.rook, color: "black"},
    // Row 2
    {type: FigureBaseTypes.pawn, color: "black"},
    {type: FigureBaseTypes.pawn, color: "black"},
    {type: FigureBaseTypes.pawn, color: "black"},
    {type: FigureBaseTypes.pawn, color: "black"},
    {type: FigureBaseTypes.pawn, color: "black"},
    {type: FigureBaseTypes.pawn, color: "black"},
    {type: FigureBaseTypes.pawn, color: "black"},
    {type: FigureBaseTypes.pawn, color: "black"},
    // Row 3
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    // Row 4
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    // Row 5
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    // Row 6
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    {type: null, color: null},
    // Row 7
    {type: FigureBaseTypes.pawn, color: "white"},
    {type: FigureBaseTypes.pawn, color: "white"},
    {type: FigureBaseTypes.pawn, color: "white"},
    {type: FigureBaseTypes.pawn, color: "white"},
    {type: FigureBaseTypes.pawn, color: "white"},
    {type: FigureBaseTypes.pawn, color: "white"},
    {type: FigureBaseTypes.pawn, color: "white"},
    {type: FigureBaseTypes.pawn, color: "white"},
    // Row 8
    {type: FigureBaseTypes.rook, color: "white"},
    {type: FigureBaseTypes.knight, color: "white"},
    {type: FigureBaseTypes.bishop, color: "white"},
    {type: FigureBaseTypes.queen, color: "white"},
    {type: FigureBaseTypes.king, color: "white"},
    {type: FigureBaseTypes.bishop, color: "white"},
    {type: FigureBaseTypes.knight, color: "white"},
    {type: FigureBaseTypes.rook, color: "white"},
];